@startuml

interface "JSBSim interface" as JSBi
interface "JCS interface" as JCSi

package "JFP" {
    [FCS interface]
    [FDM interfrace]
    [Visualization]
}

package "JCS" {
    [XML parser]
    [HAL]
    [Control system objects]
    [Data interface]
}

JSBi - [JSBSim]
[FDM interfrace] --> JSBi

JCSi - [Data interface]
[FCS interface] --> JCSi

@enduml